[package]
name = "guess"
version = "0.1.0"
edition = "2021"
authors = ["Rickers <hi@ho.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"

[profile.release]
panic = 'abort'
